spring:
  config:
    activate:
      on-profile: prod
  ## datasource 설정
  datasource:
    hikari:
      cozubu:
        jdbc-url: jdbc:log4jdbc:mysql://115.143.85.142:3306/ace?characterEncoding=UTF-8&serverTimezone=UTC
        username: ace
        password: aceepdlxjqpdltm1!
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        # driver-class-name: org.mariadb.jdbc.Driver
        pool-name: default-cozubu-pool
  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: false
  jwt:
    secret: govlepel@$&


file:
  upload-dir: /home/tomcat/img/

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace