spring:
  config:
    activate:
      on-profile: prod
  ## datasource 설정
  datasource:
    hikari:
      cozubu:
        jdbc-url: url
        username: username
        password: password
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        # driver-class-name: org.mariadb.jdbc.Driver
        pool-name: default-cozubu-pool
  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: false
  jwt:
    secret: secret


file:
  upload-dir: /home/tomcat/img/

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
